services:
  web:
    build: .
    ports:
      - "8890:8888"
      - "8000:8000"
    volumes:
      - .:/home/jovyan
    restart: unless-stopped
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  postgres:
    image: chriseaton/adventureworks:postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    restart: unless-stopped
    ports: 
      - "5433:5432"


